POST http://localhost:7777/events
Content-Type: application/json

{
  "title": 123,
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:7777/events/3c9e0dcb-39b4-4e08-874d-899f9410b4fe/attendees
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br"
}

###

GET http://localhost:7777/events/3c9e0dcb-39b4-4e08-874d-899f9410b4fe

###

GET http://localhost:7777/attendees/1/badge

###

GET http://localhost:7777/attendees/3/check-in

###

GET http://localhost:7777/events/5718beda-e654-409c-9558-0ec79f53c962/attendees

###